# build like `docker build -t rcheologyr2 -f Dockerfile-R2 .`
# run like `docker run --name rcheologyr2_container rcheologyr2`

FROM yamamuteki/ubuntu-lucid-i386

WORKDIR /rcheology
RUN mkdir docker-data
VOLUME /rcheology/docker-data

COPY lucid.sources.list /etc/apt/sources.list
RUN apt-get -y update
# this seems to install much less than `apt-get build-dep r-base-core`
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q r-base-core xorg-dev tclx8.4-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q wget 

COPY install-R-2.x-versions.sh .
RUN chmod a+x install-R-2.x-versions.sh
COPY list-objects.R .
COPY R-2.x-source-versions.txt .

CMD ["./install-R-2.x-versions.sh"]

