# build like `docker build -t potato -f Dockerfile-potato .`
# run like `docker run --name potato potato`

FROM debian/eol:potato

WORKDIR /rcheology
RUN mkdir docker-data
VOLUME /rcheology/docker-data

RUN apt-get -y update
# this seems to install much less than `apt-get build-dep r-base-core`
#RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q build-essential atlas2-dev blas-dev g77 f2c tk8.0-dev xvfb xbase-clients
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q wget 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q vim
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -q man

COPY install-R-source-versions.sh .
RUN chmod a+x install-R-source-versions.sh
COPY list-objects.R .
COPY R-versions-potato.txt ./R-versions.txt

CMD ["./install-R-source-versions.sh"]
