---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# rcheology

A data package which lists every command in base R packages since R version 3.0.2.

## Installing

```{r, eval = FALSE}
install.packages("remotes") # if you need to
remotes::install_github("hughjonesd/rcheology")
```

## Running it yourself

* Install docker.
* Source `gather-data.R` to:
    - build the image
    - run the container
    - get data out of the container

## The data

You can view the data online in a [Shiny app](https://hughjonesd.shinyapps.io/rcheology/).

```{r}
library(rcheology)
data("rcheology")

head(rcheology)
```

Base functions over time:

```{r}

rvs <- unique(rcheology$Rversion)

palette(rainbow(7))
barplot(xtabs(~ Rversion + package, data = rcheology), 
        beside = TRUE, 
        las    = 2, 
        border = NA, 
        col    = heat.colors(length(rvs)),
        ylab   = "Number of objects"
      )
```

